services:
  postgres:
    image: postgres:16-alpine
    container_name: devboard-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devboard_user
      POSTGRES_PASSWORD: devboard_pass
      POSTGRES_DB: devboard
    ports:
      - '5433:5432'
    volumes:
      - devboard_data:/var/lib/postgresql/data

volumes:
  devboard_data: